SELECT TOP (1000) [Id]
      ,[weddingDate]
      ,[placeConvite]
      ,[adressConvite]
      ,[hourDinnerConvite]
      ,[transportConvite]
      ,[hourTransportConvite]
      ,[boyPhone]
      ,[girlPhone]
      ,[pinCode]
      ,[cityIdProvince]
      ,[coupleName]
      ,[idCity]
      ,[idUsuario]
      ,[usuarioId]
  FROM [Wedding].[dbo].[Invitations]